In [1]:
import pandas as pd

models = [
    # english models
    "meta-llama/Meta-Llama-3.1-8B",
    "meta-llama/Llama-3.1-8B-Instruct",
    "google/gemma-2-9b",
    "google/gemma-2-9b-it",
    # chinese models
    "Qwen/Qwen2.5-7B",
    "Qwen/Qwen2.5-7B-Instruct",
    "deepseek-ai/deepseek-llm-7b-base",
    "deepseek-ai/deepseek-llm-7b-chat",
    # arabic models
    "inceptionai/jais-13b",
    "inceptionai/jais-13b-chat",
    "inceptionai/Jais-2-8B-Chat",
    "FreedomIntelligence/AceGPT-v2-8B",
    "FreedomIntelligence/AceGPT-v2-8B-Chat",
    # mistral models
    "mistralai/Ministral-3-8B-Base-2512",
    "mistralai/Ministral-3-8B-Instruct-2512", # not done
    # greek models
    "ilsp/Llama-Krikri-8B-Instruct",
    "ilsp/Meltemi-7B-Instruct-v1.5",
    # hindi models
    "sarvamai/OpenHathi-7B-Hi-v0.1-Base",
    "krutrim-ai-labs/Krutrim-1-instruct", # not done
    # southeast asian models
    "aisingapore/Llama-SEA-LION-v3-8B",
    "aisingapore/Llama-SEA-LION-v3-8B-IT",
    "SeaLLMs/SeaLLM-7B-v2.5", # instruct
    "SeaLLMs/SeaLLMs-v3-7B",
    "SeaLLMs/SeaLLMs-v3-7B-Chat",
    # korean models
    "naver-hyperclovax/HyperCLOVAX-SEED-Omni-8B", # instruct not done
    "beomi/Llama-3-Open-Ko-8B",
    "EleutherAI/polyglot-ko-12.8b",
    "EleutherAI/polyglot-ko-5.8b",
    # multilingual models
    "CohereLabs/aya-expanse-8b"  # instruct
]

subsets = [
    "english_ca",
    "chinese_ca",
    "chinese_cs",
    "chinese_cs_en",
    "arabic_ca",
    "arabic_cs",
    "arabic_cs_en",
    "greek_ca",
    "greek_cs",
    "greek_cs_en",
    "hindi_ca",
    "hindi_cs",
    "hindi_cs_en",
    "indonesian_ca",
    "indonesian_cs",
    "indonesian_cs_en",
    "korean_ca",
    "korean_cs",
    "korean_cs_en",
]


df = pd.read_csv("lite_eval_results_loglik_v1_5_filtered.csv")

# Reorder columns: keep 'model', 'country', then all `subsets` in order if present
cols = ['model', 'country'] + [s for s in subsets if s in df.columns]
# In case there are some other columns (unlikely), append them at the end
cols += [c for c in df.columns if c not in cols]
df = df[cols]

# Reorder rows: order by 'model' in the order of the `models` list (if model column exists)
if "model" in df.columns:
    df["model"] = pd.Categorical(df["model"], categories=models, ordered=True)
    df = df.sort_values('model')

# Save reordered DataFrame back to original CSV to cover old file
df.to_csv("lite_eval_results_loglik_v1_filtered.csv", index=False)

# Show the DataFrame after reordering
df

,model,country,english_ca,chinese_ca,chinese_cs,chinese_cs_en,arabic_ca,arabic_cs,arabic_cs_en,greek_ca,...,greek_cs_en,hindi_ca,hindi_cs,hindi_cs_en,indonesian_ca,indonesian_cs,indonesian_cs_en,korean_ca,korean_cs,korean_cs_en
21,meta-llama/Meta-Llama-3.1-8B,USA,0.6200,0.5253,0.4825,0.4915,0.4203,0.4595,0.5766,0.4553,...,0.7503,0.4057,0.427,0.605,0.4971,0.6038,0.6397,0.4461,0.266,0.453
20,meta-llama/Llama-3.1-8B-Instruct,USA,0.6448,0.5588,0.5075,0.4825,0.4747,0.5355,0.5606,0.4801,...,0.7543,0.4514,0.469,0.593,0.5403,0.6537,0.6477,0.4883,0.367,0.464
16,google/gemma-2-9b,USA,0.6856,0.5773,0.4436,0.4785,0.5170,0.5015,0.5636,0.4874,...,0.7583,0.5442,0.510,0.630,0.5559,0.6018,0.6347,0.5277,0.400,0.421
15,google/gemma-2-9b-it,USA,0.7055,0.6186,0.5435,0.5005,0.5661,0.5636,0.5636,0.5675,...,0.7816,0.5705,0.507,0.633,0.6156,0.6966,0.6737,0.5768,0.403,0.456
6,Qwen/Qwen2.5-7B,China,0.7143,0.6565,0.8122,0.6623,0.5534,0.5445,0.5716,0.4519,...,0.7594,0.4636,0.434,0.533,0.6166,0.6567,0.6687,0.5826,0.455,0.478
5,Qwen/Qwen2.5-7B-Instruct,China,0.6375,0.6676,0.8102,0.6034,0.5248,0.5475,0.4745,0.3567,...,0.6036,0.4577,0.413,0.438,0.5943,0.6507,0.6138,0.5573,0.420,0.407
13,deepseek-ai/deepseek-llm-7b-base,China,0.2886,0.2041,0.2418,0.2867,0.2046,0.2352,0.2803,0.2055,...,0.3670,0.1983,0.201,0.334,0.2347,0.2685,0.2874,0.2138,0.138,0.233
14,deepseek-ai/deepseek-llm-7b-chat,China,0.3649,0.2036,0.2338,0.3197,0.1574,0.1892,0.3504,0.1900,...,0.4874,0.1842,0.198,0.392,0.2561,0.2585,0.4002,0.1992,0.122,0.337
19,inceptionai/Jais-2-8B-Chat,UAE,0.5831,0.3795,0.3397,0.4256,0.5029,0.7017,0.5706,0.2682,...,0.6400,0.2959,0.278,0.426,0.2998,0.3503,0.5798,0.2638,0.230,0.338
4,FreedomIntelligence/AceGPT-v2-8B,UAE,0.2250,0.2240,0.2557,0.2557,0.2250,0.2462,0.2462,0.2250,...,0.2508,0.2250,0.229,0.229,0.2250,0.2575,0.2575,0.2235,0.115,0.115
3,FreedomIntelligence/AceGPT-v2-8B-Chat,UAE,0.4990,0.4242,0.4296,0.3546,0.4407,0.5115,0.4294,0.4568,...,0.6289,0.3212,0.343,0.446,0.4470,0.5719,0.5130,0.4145,0.229,0.282
22,mistralai/Ministral-3-8B-Base-2512,France,0.7342,0.6696,0.6294,0.5205,0.6093,0.6076,0.6146,0.6152,...,0.8129,0.6395,0.621,0.653,0.6535,0.7146,0.7016,0.6069,0.492,0.531
17,ilsp/Llama-Krikri-8B-Instruct,Greece,0.6064,0.4942,0.4316,0.4486,0.4018,0.4735,0.5185,0.5369,...,0.7644,0.4096,0.382,0.560,0.4874,0.5749,0.6347,0.4402,0.297,0.446
18,ilsp/Meltemi-7B-Instruct-v1.5,Greece,0.5073,0.3465,0.2977,0.4106,0.2745,0.2372,0.4484,0.4242,...,0.6936,0.2546,0.280,0.481,0.3576,0.4142,0.5579,0.3465,0.321,0.381
23,sarvamai/OpenHathi-7B-Hi-v0.1-Base,India,0.3499,0.2818,0.2667,0.3217,0.2396,0.2212,0.3283,0.2196,...,0.4459,0.2828,0.314,0.370,0.2731,0.2914,0.3723,0.2468,0.229,0.244
11,aisingapore/Llama-SEA-LION-v3-8B,Southeast Asian,0.6463,0.5112,0.4685,0.4795,0.4266,0.4565,0.5485,0.4636,...,0.7563,0.4261,0.439,0.598,0.5131,0.6198,0.6487,0.4553,0.341,0.460
10,aisingapore/Llama-SEA-LION-v3-8B-IT,Southeast Asian,0.6948,0.5831,0.4585,0.4406,0.5321,0.5235,0.5225,0.5160,...,0.7270,0.4587,0.386,0.573,0.5996,0.6527,0.6527,0.5369,0.383,0.384
7,SeaLLMs/SeaLLM-7B-v2.5,Southeast Asian,0.6293,0.5360,0.4765,0.4835,0.4883,0.5095,0.5766,0.4786,...,0.7604,0.4684,0.480,0.609,0.5262,0.6367,0.6457,0.4859,0.413,0.463
9,SeaLLMs/SeaLLMs-v3-7B,Southeast Asian,0.6851,0.6293,0.8541,0.5624,0.4932,0.4885,0.5506,0.3950,...,0.7705,0.4320,0.453,0.590,0.5656,0.6317,0.6647,0.5311,0.400,0.492
8,SeaLLMs/SeaLLMs-v3-7B-Chat,Southeast Asian,0.6876,0.6220,0.8551,0.5794,0.4947,0.4695,0.5475,0.4291,...,0.7735,0.4189,0.446,0.594,0.5923,0.6627,0.6697,0.5000,0.419,0.457
12,beomi/Llama-3-Open-Ko-8B,South Korea,0.5010,0.3260,0.2957,0.3906,0.2478,0.2643,0.4875,0.2634,...,0.6532,0.3338,0.314,0.488,0.3567,0.3772,0.5140,0.3571,0.263,0.339
1,EleutherAI/polyglot-ko-12.8b,South Korea,0.2434,0.2221,0.2557,0.2517,0.2177,0.2462,0.2272,0.2104,...,0.2730,0.1963,0.223,0.249,0.2328,0.2655,0.2705,0.2245,0.211,0.206
2,EleutherAI/polyglot-ko-5.8b,South Korea,0.2313,0.2230,0.2557,0.2527,0.2143,0.2462,0.2452,0.2104,...,0.2396,0.1924,0.225,0.227,0.2167,0.2675,0.2515,0.2221,0.116,0.169
0,CohereLabs/aya-expanse-8b,Multilingual,0.5549,0.4893,0.4725,0.4346,0.4611,0.5405,0.5145,0.4849,...,0.6896,0.4286,0.393,0.508,0.4713,0.5679,0.5749,0.4485,0.232,0.324

In [7]:
import pandas as pd

models = [
    # english models
    "meta-llama/Meta-Llama-3.1-8B",
    "meta-llama/Llama-3.1-8B-Instruct",
    "google/gemma-2-9b",
    "google/gemma-2-9b-it",
    # chinese models
    "Qwen/Qwen2.5-7B",
    "Qwen/Qwen2.5-7B-Instruct",
    "deepseek-ai/deepseek-llm-7b-base",
    "deepseek-ai/deepseek-llm-7b-chat",
    # arabic models
    "inceptionai/jais-13b",
    "inceptionai/jais-13b-chat",
    "inceptionai/Jais-2-8B-Chat",
    "FreedomIntelligence/AceGPT-v2-8B",
    "FreedomIntelligence/AceGPT-v2-8B-Chat",
    # # mistral models
    # "mistralai/Ministral-3-8B-Base-2512",
    # "mistralai/Ministral-3-8B-Instruct-2512", # not done
    # # greek models
    # "ilsp/Llama-Krikri-8B-Instruct",
    # "ilsp/Meltemi-7B-Instruct-v1.5",
    # # hindi models
    # "sarvamai/OpenHathi-7B-Hi-v0.1-Base",
    # "krutrim-ai-labs/Krutrim-1-instruct", # not done
    # # southeast asian models
    # "aisingapore/Llama-SEA-LION-v3-8B",
    # "aisingapore/Llama-SEA-LION-v3-8B-IT",
    # "SeaLLMs/SeaLLM-7B-v2.5", # instruct
    # "SeaLLMs/SeaLLMs-v3-7B",
    # "SeaLLMs/SeaLLMs-v3-7B-Chat",
    # # korean models
    # "naver-hyperclovax/HyperCLOVAX-SEED-Omni-8B", # instruct not done
    # "beomi/Llama-3-Open-Ko-8B",
    # "EleutherAI/polyglot-ko-12.8b",
    # "EleutherAI/polyglot-ko-5.8b",
    # # multilingual models
    # "CohereLabs/aya-expanse-8b"  # instruct
]

subsets = [
    "english_ca",
    "chinese_ca",
    "chinese_cs",
    "chinese_cs_en",
    "arabic_ca",
    "arabic_cs",
    "arabic_cs_en",
    "greek_ca",
    "greek_cs",
    "greek_cs_en",
    "hindi_ca",
    "hindi_cs",
    "hindi_cs_en",
    "indonesian_ca",
    "indonesian_cs",
    "indonesian_cs_en",
    "korean_ca",
    "korean_cs",
    "korean_cs_en",
]

df = pd.read_csv("lite_eval_results_v1_filtered.csv")

# Only keep rows with selected models and only keep relevant columns: model, country, and relevant subsets
df = df[df["model"].isin(models)]
columns_to_keep = ["model", "country"] + [s for s in subsets if s in df.columns]
df = df[columns_to_keep]

# Optionally, sort according to the model list
df["model"] = pd.Categorical(df["model"], categories=models, ordered=True)
df = df.sort_values("model").reset_index(drop=True)

# Show the transposed DataFrame
df.transpose()

,0,1,2,3,4,5,6,7,8,9,10
model,meta-llama/Meta-Llama-3.1-8B,meta-llama/Llama-3.1-8B-Instruct,google/gemma-2-9b,google/gemma-2-9b-it,Qwen/Qwen2.5-7B,Qwen/Qwen2.5-7B-Instruct,deepseek-ai/deepseek-llm-7b-base,deepseek-ai/deepseek-llm-7b-chat,inceptionai/jais-13b,inceptionai/Jais-2-8B-Chat,FreedomIntelligence/AceGPT-v2-8B-Chat
country,USA,USA,USA,USA,China,China,China,China,UAE,UAE,UAE
english_ca,0.5748,0.5452,0.6565,0.673,0.7196,0.7153,0.3975,0.4626,0.31,0.5811,0.6147
chinese_ca,0.5219,0.4456,0.5884,0.3372,0.6749,0.6686,0.381,0.4606,0.1958,0.3834,0.5185
chinese_cs,0.4655,0.4615,0.4935,0.4386,0.8422,0.8012,0.4306,0.5325,0.2258,0.3516,0.5145
chinese_cs_en,0.4496,0.4446,0.4895,0.5455,0.6703,0.6623,0.3217,0.4246,0.2787,0.4236,0.4915
arabic_ca,0.4086,0.4164,0.2366,0.5423,0.5447,0.5539,0.0005,0.1905,0.1968,0.4966,0.5233
arabic_cs,0.4434,0.4625,0.1522,0.5886,0.5676,0.5816,0.001,0.1712,0.2953,0.7077,0.5666
arabic_cs_en,0.5205,0.5115,0.5616,0.5846,0.6126,0.5776,0.4014,0.4555,0.3514,0.5706,0.5606
greek_ca,0.4242,0.2114,0.3615,0.533,0.448,0.4509,0.0034,0.2323,0.001,0.3387,0.481
greek_cs,0.6289,0.4985,0.5672,0.725,0.6148,0.6016,0.001,0.2032,0.0,0.4307,0.6987
greek_cs_en,0.7017,0.6977,0.7563,0.7735,0.8059,0.7968,0.4965,0.5945,0.3397,0.6471,0.7614
hindi_ca,0.3727,0.43,0.4261,0.2099,0.4397,0.465,0.1054,0.156,0.0112,0.3197,0.448
hindi_cs,0.421,0.448,0.374,0.441,0.426,0.437,0.047,0.093,0.012,0.28,0.444
hindi_cs_en,0.542,0.525,0.623,0.607,0.619,0.603,0.368,0.469,0.3,0.445,0.584
indonesian_ca,0.4179,0.4592,0.5622,0.5918,0.6127,0.6054,0.2731,0.2983,0.2133,0.397,0.5253
indonesian_cs,0.513,0.5978,0.6337,0.7315,0.6687,0.6657,0.2255,0.3852,0.2375,0.4321,0.6577
indonesian_cs_en,0.5968,0.6018,0.6228,0.6687,0.6946,0.6966,0.3882,0.5,0.3074,0.5778,0.6447
korean_ca,0.4247,0.4563,0.5044,0.3897,0.5675,0.5719,0.0044,0.3124,0.0155,0.3241,0.4845
korean_cs,0.338,0.369,0.352,0.363,0.481,0.458,0.015,0.266,0.011,0.237,0.383
korean_cs_en,0.325,0.289,0.451,0.45,0.522,0.533,0.312,0.259,0.272,0.382,0.413

In [18]:
import pandas as pd

models = [
    # english models
    "meta-llama/Meta-Llama-3.1-8B",
    "meta-llama/Llama-3.1-8B-Instruct",
    "google/gemma-2-9b",
    "google/gemma-2-9b-it",
    # chinese models
    "Qwen/Qwen2.5-7B",
    "Qwen/Qwen2.5-7B-Instruct",
    "deepseek-ai/deepseek-llm-7b-base",
    "deepseek-ai/deepseek-llm-7b-chat",
    # arabic models
    "inceptionai/jais-13b",
    "inceptionai/jais-13b-chat",
    "inceptionai/Jais-2-8B-Chat",
    "FreedomIntelligence/AceGPT-v2-8B",
    "FreedomIntelligence/AceGPT-v2-8B-Chat",
    # mistral models
    "mistralai/Ministral-3-8B-Base-2512",
    "mistralai/Ministral-3-8B-Instruct-2512", # not done
    # greek models
    "ilsp/Llama-Krikri-8B-Instruct",
    "ilsp/Meltemi-7B-Instruct-v1.5",
    # hindi models
    "sarvamai/OpenHathi-7B-Hi-v0.1-Base",
    "krutrim-ai-labs/Krutrim-1-instruct", # not done
    # southeast asian models
    "aisingapore/Llama-SEA-LION-v3-8B",
    "aisingapore/Llama-SEA-LION-v3-8B-IT",
    "SeaLLMs/SeaLLM-7B-v2.5", # instruct
    "SeaLLMs/SeaLLMs-v3-7B",
    "SeaLLMs/SeaLLMs-v3-7B-Chat",
    # korean models
    "naver-hyperclovax/HyperCLOVAX-SEED-Omni-8B", # instruct not done
    "beomi/Llama-3-Open-Ko-8B",
    "EleutherAI/polyglot-ko-12.8b",
    "EleutherAI/polyglot-ko-5.8b",
    # multilingual models
    "CohereLabs/aya-expanse-8b"  # instruct
]

df = pd.read_csv("gap_results.csv")

# Only keep rows with selected models
df = df[df["model"].isin(models)]

# Keep only model, country, and *_knowledge_gap columns
knowledge_gap_cols = [col for col in df.columns if col.endswith("_knowledge_gap")]
columns_to_keep = ["model", "country"] + knowledge_gap_cols
df = df[columns_to_keep]

# Optionally, sort according to the model list
df["model"] = pd.Categorical(df["model"], categories=models, ordered=True)
df = df.sort_values("model").reset_index(drop=True)
df
# Show the transposed DataFrame
# df.transpose()

,model,country,chinese_knowledge_gap,arabic_knowledge_gap,greek_knowledge_gap,hindi_knowledge_gap,indonesian_knowledge_gap,korean_knowledge_gap
0,meta-llama/Meta-Llama-3.1-8B,USA,0.0688,0.0891,0.0778,0.0811,0.0731,0.1631
1,meta-llama/Llama-3.1-8B-Instruct,USA,0.1165,0.0798,0.1346,0.0382,0.0820,0.1689
2,google/gemma-2-9b,USA,0.0721,0.0105,0.1059,-0.0186,0.1052,0.0531
3,google/gemma-2-9b-it,USA,0.2289,0.1347,0.0915,0.2971,0.1440,0.1963
4,Qwen/Qwen2.5-7B,China,0.2166,0.1299,0.0805,0.0869,0.0810,0.1111
5,Qwen/Qwen2.5-7B-Instruct,China,0.1856,0.1654,0.0692,0.0843,0.0790,0.0684
6,deepseek-ai/deepseek-llm-7b-base,China,0.1254,-0.0034,-0.1014,-0.0289,-0.0383,0.0961
7,deepseek-ai/deepseek-llm-7b-chat,China,0.1099,-0.0122,-0.1610,-0.0694,0.0495,0.1572
8,inceptionai/jais-13b,UAE,0.0613,0.0571,-0.0307,0.0108,0.0268,0.0335
9,inceptionai/Jais-2-8B-Chat,UAE,0.1257,0.2216,0.0260,0.0964,0.0384,0.1120
10,FreedomIntelligence/AceGPT-v2-8B-Chat,UAE,0.1192,0.0974,0.0710,0.0267,0.1024,0.1002
11,ilsp/Llama-Krikri-8B-Instruct,Greece,0.0284,0.0524,0.1418,0.0486,0.0053,0.1521
12,ilsp/Meltemi-7B-Instruct-v1.5,Greece,0.0110,0.0730,0.0502,0.0709,0.0399,0.1284
13,sarvamai/OpenHathi-7B-Hi-v0.1-Base,India,-0.0170,0.0024,-0.0001,0.1200,0.0087,0.0204
14,aisingapore/Llama-SEA-LION-v3-8B,Southeast Asian,0.0873,0.0951,0.0643,0.0384,0.0854,0.1302
15,aisingapore/Llama-SEA-LION-v3-8B-IT,Southeast Asian,0.0841,0.0845,0.0747,0.0409,0.0525,0.1098
16,SeaLLMs/SeaLLM-7B-v2.5,Southeast Asian,-0.1387,0.0881,0.0356,-0.0227,0.1116,0.0859
17,SeaLLMs/SeaLLMs-v3-7B,Southeast Asian,0.3069,0.0943,-0.0094,0.0624,0.0483,0.1238
18,SeaLLMs/SeaLLMs-v3-7B-Chat,Southeast Asian,0.2961,0.1149,0.0869,0.0992,-0.0123,0.0686
19,beomi/Llama-3-Open-Ko-8B,South Korea,0.1737,0.0364,-0.1934,-0.0034,0.0077,0.1182
20,EleutherAI/polyglot-ko-12.8b,South Korea,-0.0304,-0.0142,-0.0498,-0.0490,-0.0068,0.0102
21,CohereLabs/aya-expanse-8b,Multilingual,0.0436,0.0134,0.1042,0.0276,-0.1155,0.1472